---
- name: Delete superset dir for sec_installation
  shell: rm -rf /data/memcached

- name: Create dir for superset
  file:
    path: "/data/memcached"
    state: directory
    recurse: yes

- name: Clone superset in Websoft9 
  git:
    repo: "{{memcached_git_url}}"
    dest: "/data/memcached"

- name: Run the docker-compose
  shell: |
    docker-compose -f docker-compose.yml up -d
    sleep 30
  args:
    chdir: /data/memcached
